### PR TITLE
Manual installation + Julia wrapper for penbmi function

### PR DESCRIPTION
**Pull request by blegat**
This adds manual installation instructions to install penbmi as well as wrapping the C function with a Julia function and a basic test based on the example given with penbmi.

On my computer, running the tests give:
```

vars       :     3
constr     :     4
mconstr    :     1
msizes     :     3

********************************************* 
PENBMI 2.1
------------

*********************************************



********************************************************************************
* it |     obj      |     opt      |     feas     |   <U,A(x)>   | Nwt  |  LS  *
********************************************************************************
|   0|   0.0000e+00 |   7.5763e-08 |   4.5183e+00 |   1.2500e+02 |    0 |    0 |
|   1|   7.8275e+00 |   2.1625e-03 |   0.0000e+00 |   7.1953e+00 |   27 |   27 |
|   2|   3.8779e+00 |   3.7622e-03 |   1.6252e-01 |   4.0844e-01 |   31 |   33 |
|   3|   3.9733e+00 |   2.5533e-02 |   6.5687e-02 |   8.2627e-02 |   32 |   34 |
|   4|   4.0316e+00 |   2.9491e-02 |   7.1571e-03 |   1.5194e-02 |   33 |   35 |
|   5|   4.0431e+00 |   3.1881e-03 |   0.0000e+00 |   6.3835e-03 |   34 |   36 |
|   6|   4.0391e+00 |   1.1232e-03 |   0.0000e+00 |   8.5027e-04 |   35 |   37 |
|   7|   4.0388e+00 |   3.3832e-05 |   0.0000e+00 |   1.6736e-04 |   36 |   38 |
|   8|   4.0387e+00 |   5.3884e-06 |   0.0000e+00 |   2.3343e-05 |   37 |   39 |
|   9|   4.0387e+00 |   7.5281e-08 |   0.0000e+00 |   4.1882e-06 |   38 |   40 |
|  10|   4.0387e+00 |   1.3113e-09 |   0.0000e+00 |   8.2625e-07 |   39 |   41 |
|  11|   4.0387e+00 |   1.5451e-11 |   0.0000e+00 |   1.7077e-07 |   40 |   42 |
|  12|   4.0387e+00 |   2.2199e-13 |   0.0000e+00 |   3.5759e-08 |   41 |   43 |
|  13|   4.0387e+00 |   2.2199e-13 |   0.0000e+00 |   7.5667e-09 |   42 |   93 |


********************************************************************************
F(x_13) =                         4.0386976747102246E+00
f(x_13) =                         4.0386978216703939E+00
||f(x_13) -  F(x_13)|| =          1.4696016936710521E-07
||f(x_13) -  f(x_12)|| =          0.0000000000000000E+00
Feasibility (LI)                 -3.1887107050726876E-01
Slackness (LI)                    7.5107834552811907E-09
Feasibility (BMI)                 0.0000000000000000E+00
Slackness   (BMI)                 5.5900895024052488E-11
||grad_x(L(x,U))||                7.5763117809832070E-08
lambda_min(hess_x(L(x,U)))  >=   -0.0000000000000000E+00
Outer Iterations                                      13
Inner Iterations                                      42
Linesearch steps                                      93
Start time                      Thu Aug  8 14:56:27 2019
End time                        Thu Aug  8 14:56:27 2019
Real time                              0 h  0 min  0 sec
Process time (total)                         0.00138 sec
********************************************************************************



Stopped by linesearch failure. Result may be wrong.

PENBMI failed.
Test Summary:  | Pass  Total
Penbmi example |    6      6
Test.DefaultTestSet("Penbmi example", Any[], 6, false)
```

cc @kocvara

### CODE REVIEW

**Comment by kocvara** [comment]
Hi Benoit,

I downloaded everything in the bl/penbmi branch in my local directory 
.julia/packages/Penopt/6RCzO 
and followed your instructions to create the deps folder and the deps.jl file in it. I am on Mac, so I compiled an .so library of penbmi and placed it in deps/usr/lib, as instructed.

Trying to run the test, I said (in julia)

using JuMP
using Penopt
import Pkg; Pkg.add("Test")
using Pkg; Pkg.test("Penopt”)

and got the error message shown below. So it seems that penbmi wasn’t even called yet. When I do it with SeDuMi, the test runs fine. Running import Pkg; Pkg.add("Test”) again doesn’t help. Can you help? It seems that I still need to install or set up something relating Penopt(?). 

Thanks,
Michal


julia> using Pkg; Pkg.test("Penopt")
   Testing Penopt
    Status `/var/folders/zs/rqfnjvys7z9fb1lxymgxsb240000gn/T/tmpQAf1PK/Manifest.toml`
  [fb8f6f4e] Penopt v0.0.0 #master (https://github.com/JuliaOpt/Penopt.jl.git)
  [8f399da3] Libdl  [`@stdlib/Libdl`]
ERROR: LoadError: LoadError: ArgumentError: Package Test not found in current path:
- Run `import Pkg; Pkg.add("Test")` to install the Test package.

Stacktrace:
 [1] require(::Module, ::Symbol) at ./loading.jl:823
 [2] include at ./boot.jl:326 [inlined]
 [3] include_relative(::Module, ::String) at ./loading.jl:1038
 [4] include(::Module, ::String) at ./sysimg.jl:29
 [5] include(::String) at ./client.jl:403
 [6] top-level scope at none:0
 [7] include at ./boot.jl:326 [inlined]
 [8] include_relative(::Module, ::String) at ./loading.jl:1038
 [9] include(::Module, ::String) at ./sysimg.jl:29
 [10] include(::String) at ./client.jl:403
 [11] top-level scope at none:0
in expression starting at /Users/michal/.julia/packages/Penopt/6RCzO/test/bmi.jl:2
in expression starting at /Users/michal/.julia/packages/Penopt/6RCzO/test/runtests.jl:1
ERROR: Package Penopt errored during testing
Stacktrace:
 [1] pkgerror(::String, ::Vararg{String,N} where N) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.1/Pkg/src/Types.jl:120
 [2] #test#66(::Bool, ::Function, ::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.1/Pkg/src/Operations.jl:1329
 [3] #test at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.1/Pkg/src/API.jl:0 [inlined]
 [4] #test#46(::Bool, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.1/Pkg/src/API.jl:198
 [5] test at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.1/Pkg/src/API.jl:183 [inlined]
 [6] #test#45 at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.1/Pkg/src/API.jl:180 [inlined]
 [7] test at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.1/Pkg/src/API.jl:180 [inlined]
 [8] #test#44 at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.1/Pkg/src/API.jl:179 [inlined]
 [9] test at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.1/Pkg/src/API.jl:179 [inlined]
 [10] #test#43(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::String) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.1/Pkg/src/API.jl:178
 [11] test(::String) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.1/Pkg/src/API.jl:178
 [12] top-level scope at none:0

**Comment by blegat** [comment]
@kocvara This should be fixed by e3a2000cee53e9e061c0284d5f78220fbf721305

**Comment by kocvara** [comment]
Great, it works now, thanks. Two of the tests did not pass but that’s because of a different system and libs and perhaps also slightly different initial settings. 

BEst,
Michal

**Comment by kocvara** [comment]
I am now confused by the naming:

model = Model(with_optimizer(Penbmi.Optimizer))
ERROR: UndefVarError: Penbmi not defined

and 

model = Model(with_optimizer(Penopt.Optimizer))
ERROR: UndefVarError: Optimizer not defined

**Comment by blegat** [comment]
> Two of the tests did not pass but that’s because of a different system and libs and perhaps also slightly different initial settings.

Yes, the tests are definitely too tight, should be fixed in 0861d62

> WARNING: This is a work in progress, don't trust anything written below.

Yes, that's the reason of the warning at the beginning of the README, this will work once have have the MathOptInterface wrapper.

**Comment by kocvara** [comment]
Re tests: Problematic are the iresults, I am getting 
Evaluated: Int32[13, 40, 43, 0] ≈ [13, 42, 93, 0]
because the linesearch goes slightly differently; I also finish without the error message:
  Expression: info == 3
   Evaluated: 0 == 3
Perhaps we should just test for the reals?

**Comment by blegat** [comment]
> Perhaps we should just test for the reals?

Sounds good, done in fd4ffe5

**Comment by kocvara** [comment]
Test Summary:  | Pass  Total
Penbmi example |    7      7
   Testing Penopt tests passed

**Pull request merged**
